### ISSUE TITLE
Missing wasm files for 2021-Q1 result

### ISSUE THREAD

**Issue by 0yi0** [jedisct1/webassembly-benchmarks#1]
I was checking [the errors on ssvm](https://github.com/jedisct1/webassembly-benchmarks/tree/master/2021-Q1/output/linux-x86_64/ssvm) (which was moved to [WasmEdge](https://github.com/WasmEdge/WasmEdge) now), and found that [one of the errors](https://github.com/jedisct1/webassembly-benchmarks/tree/master/2021-Q1/output/linux-x86_64/ssvm/sign.log) were from a benchmark which I couldn't find its wasm file.

Here's a list of missing benchmarks by comparing the list of logs and wasm files:
- `aead_aes256gcm`
- `aead_aes256gcm2`
- `misuse`
- `sign`
- `sodium_version`

It would be nice to know where to find or how to generate these benchmarks.

**Comment by jedisct1** [comment]
Hi!

`aes256_gcm`, `aes256_gcm2`, `misuse` and `sodium_version` don't do anything (AES256 is not available in WebAssembly, `misuse` requires segfault handlers, and `sodium_version` just returns a constant). So they've been skipped.

`sign` looks like something I forgot to add to the repository. I'm going to add it :)

These benchmarks can be built by running the `dist-build/wasm32-wasi.sh --bench` command:

```sh
git clone --branch=stable https://github.com/jedisct1/libsodium

cd libsodium

./dist-build/wasm32-wasi.sh --bench
```

Of course, this requires `zig` to be installed in order to compile C code to WebAssembly.

The `WASI_RUNTIME` environment can be set to `wavm`, `wasmtime`, `wasmer`, `wasm3`, `iwasm`, `ssvm`, `node` or `wasmer-js` to use a specific runtime. See the `test/default/wasi-test-wrapper.sh` script that actually runs the benchmarks.

For each test, a `.log` file is created with the time it took for the test to complete. The same tests can also run in web browsers: https://download.libsodium.org/libsodium.js/browsers-test/

**Comment by jedisct1** [comment]
Ah, I remember why `sign` was not included. On WebAssembly, signatures are deterministic; a single iteration is performed, which is not enough to get a relevant benchmark.

**Comment by sajaghori** [comment]
Hi, following this steps, it doesn't produce the .wasm files. Can you give me a hint on how you produced the .wasm files?

**Comment by jedisct1** [comment]
@sajaghori What does the script print? Do you get any errors ?

With the current versions of `libsodium`, that script is not even required any more, you can directly run, from the base directory:

```sh
zig build -Dtarget=wasm32-wasi -Drelease-fast -Denable_benchmarks=true
```

And the benchmarks end up in the `zig-out/bin/` directory.

**Comment by sajaghori** [comment]
Awesome that helped!
